import { StyleSheet, Dimensions } from "react-native";

export const cores = {
  fundo: "#cffeff",
  branco: "#ffffff",
  preto: "#000000",
  primario: "#0097A7",
  destaque: "#00b3bf",
  inputBorder: "#2b9aa0",
  sombra: "#b5e9ea",
};

const { width } = Dimensions.get("window");
const dayButtonSize = width * 0.11;

const estiloMedicamento = StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: cores.fundo,
    alignItems: "center",
    justifyContent: "flex-start",
    padding: "5%",
  },
  tituloTela: {
    fontSize: 35,
    fontWeight: "bold",
    marginBottom: "3%",
    marginTop: "8%",
    color: cores.primario,
    textAlign: "center",
  },
  input: {
    width: "100%",
    height: 45,
    borderColor: cores.inputBorder,
    borderWidth: 2,
    borderRadius: 8,
    paddingHorizontal: 10,
    marginBottom: "4%",
    backgroundColor: cores.branco,
    color: cores.preto,
    shadowColor: cores.sombra,
    shadowOpacity: 0.2,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  smallInput: {
    flex: 1,
    height: 45,
    borderColor: cores.inputBorder,
    borderWidth: 2,
    borderRadius: 8,
    paddingHorizontal: 10,
    marginBottom: "2%",
    backgroundColor: cores.branco,
    color: cores.preto,
    shadowColor: cores.sombra,
    shadowOpacity: 0.2,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  button: {
    backgroundColor: cores.destaque,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
    width: "80%",
    alignSelf: "center",
    marginTop: "6%",
    marginBottom: "4%",
  },
  buttonText: {
    color: cores.branco,
    fontWeight: "bold",
    fontSize: 18,
  },
  formContainer: {
    width: "100%",
    marginTop: "2%",
  },
  label: {
    fontSize: 15,
    fontWeight: "700",
    marginBottom: "1%",
    color: cores.preto,
  },
  smallRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: "2%",
  },
  selectBox: {
    height: 45,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: cores.inputBorder,
    justifyContent: "center",
    paddingHorizontal: 10,
    backgroundColor: cores.branco,
    shadowColor: cores.sombra,
    shadowOpacity: 0.2,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  selectText: {
    color: cores.preto,
    fontSize: 14,
  },
  timeInput: {
    width: "20%",
    minWidth: 80,
    backgroundColor: cores.branco,
    padding: 10,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: cores.inputBorder,
    marginRight: "2%",
    marginTop: "1%",
    textAlign: "center",
    color: cores.preto,
    shadowColor: cores.sombra,
    shadowOpacity: 0.2,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 2 },
  },
  timesRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: "2%",
  },
  timeBadge: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: cores.branco,
    borderWidth: 2,
    borderColor: cores.inputBorder,
    marginRight: "2%",
    marginBottom: "2%",
    flexDirection: "row",
    alignItems: "center",
    shadowColor: cores.sombra,
    shadowOpacity: 0.2,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 2 },
  },
  timeBadgeText: {
    marginRight: 6,
    fontWeight: "700",
    color: cores.preto,
  },
  daysRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  dayButton: {
    width: dayButtonSize,
    height: dayButtonSize,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: cores.inputBorder,
    backgroundColor: cores.branco,
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: 2,
  },
  dayButtonActive: {
    backgroundColor: cores.destaque,
    borderColor: cores.primario,
  },
  dayButtonText: {
    fontSize: 12,
    fontWeight: "700",
    color: cores.preto,
    textAlign: "center",
  },
  dayButtonTextActive: {
    color: cores.branco,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "#00000077",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: cores.branco,
    width: "80%",
    borderRadius: 8,
    paddingVertical: 20,
  },
  selectItem: {
    paddingVertical: 12,
    alignItems: "center",
  },
  selectItemText: {
    fontSize: 16,
    fontWeight: "600",
  },
  switchRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: "2%",
  },
  picker: {
  width: "100%",
  height: 50,
  backgroundColor: cores.branco,
  borderRadius: 8,
  borderWidth: 2,
  borderColor: cores.inputBorder, 
  marginBottom: "4%",
  paddingHorizontal: 10,
  color: cores.preto, 
  shadowColor: cores.sombra,
  shadowOpacity: 0.25,
  shadowRadius: 4,
  shadowOffset: { width: 0, height: 2 },
  elevation: 3, 
},

});

export default estiloMedicamento;
